name: Deploy frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t cygnetops/reacts-test -f Dockerfile.dev .
      - run: docker run -e CI=true cygnetops/reacts-test npm test

      - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB 
        uses: einaregilsson/beanstak-deploy@v18 
        with: 
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: docker-gh
          environment_name: Dockergh-env
          existing_bucket_name: elasticbeanstalk-us-east-1-894037915140
          region: us-east-1
          version_label: ${{ github.sha }}
          depolyment_package: deploy.zip